#!/usr/bin/env fish

set TDIR $XDG_CONFIG_HOME/polybar/themes
set THEMES (ls $TDIR)

if contains "$argv" $THEMES
  set THEME $argv
else if contains "$POLYBAR_THEME" $THEMES
  set THEME $POLYBAR_THEME
else
  set THEME (string collect $THEMES | sk --no-multi --height=(count . $THEMES) --no-clear -p "Select theme: ")
end

if test -z "$THEME"
  echo "No theme selected, exiting ..."
else
  set bars (cat $TDIR/$THEME/main.ini | rg -o '^\[bar/(\w+)\]' -r '$1')
  set nb (count bars)

  # Themes with multiple bars shouldn't use "main"
  if test "$nb" -gt 1
    for i in $nb
      if test "$bars[$nb]" -eq main
        set -e $bars[$nb]
        break
      end
    end
  end

  for bar in $bars
    polybar -q $bar -c $TDIR/$THEME/main.ini &
  end
end
