#!/usr/bin/env fish

set TDIR $XDG_CONFIG_HOME/polybar/themes
set THEMES (ls $TDIR)

set THEME (string collect $THEMES | sk --no-multi --height=(count . $THEMES) --no-clear -p "Select theme: ")

if test -z "$THEME"
  echo "No theme selected, exiting ..."
else
  set bars (cat $TDIR/$THEME/main.ini | rg -o '^\[bar/(\w+)\]' -r '$1')
  for bat in $bars[2..-1]
    polybar -q $bar -c $TDIR/$THEME/main.ini &
  end
end
