#!/usr/bin/env fish

set TDIR $XDG_CONFIG_HOME/polybar/themes
set THEMES (ls $TDIR)

set THEME (string collect $THEMES | sk --no-multi --height=(count . $THEMES) --no-clear -p "Select theme: ")

test -n "$THEME"
and $TDIR/$THEME/run
or echo "No theme selected, exiting ..."
